Adding libexec files, and binaries.

diff --git a/src/bin/file-io b/src/bin/file-io
--- a/src/bin/file-io
+++ b/src/bin/file-io
@@ -17,10 +17,19 @@ cmd_help ( )
 	file_io_help
 }
 
+eprintf ( )
+{
+	printf "ERROR: %s\n" "$*" 1>&2
+}
+
 disable_config ( )
 {
-	local conf_name=$1
-	local file_io_config=$2
+	local instance_dir=$1
+	local conf_name=$2
+	local file_io_config=$3
+	local user=
+	local found=
+	local home_dir=
 
 	if ! test -f $file_io_config
 	then
@@ -28,8 +37,113 @@ disable_config ( )
 		return
 	fi
 
+	source $file_io_config
+	user=$FILE_IO_USERNAME
+
 	rm -f $file_io_config
 	printf "config [$conf_name] disabled\n"
+
+	printf "checking if user [$user] is still required...\n"
+	found=$( grep "^FILE_IO_USERNAME='$user'" $instance_dir/* 2>/dev/null )
+
+	if test -z "$found"
+	then
+		home_dir=$( getent passwd $user | cut -f6 -d: )		
+		printf "no other configs require user [$user], deleting user and home directory [$home_dir]\n"
+		sudo "userdel" $user
+		sudo rm -rf $home_dir
+	fi
+
+}
+
+verify_config ( )
+{
+	local file="$1"
+
+	echo "verifying config..."
+
+	if test -z "$FILE_IO_INCOMING_DIR"
+	then
+		eprintf "FILE_IO_INCOMING_DIR not set in config [$file]"
+		exit 1
+	fi
+
+	if test -z "$FILE_IO_OUTGOING_DIR"
+	then
+		eprintf "FILE_IO_OUTGOING_DIR not set in config [$file]"
+		exit 1
+	fi
+
+	if test -z "$FILE_IO_DIR_REVERSED"
+	then
+		eprintf "FILE_IO_DIR_REVERSED not set in config [$file]"
+		exit 1
+	fi
+
+	if test -z "$FILE_IO_REGEX"
+	then
+		eprintf "FILE_IO_REGEX not set in config [$file]"
+		exit 1
+	fi
+
+	if test -z "$FILE_IO_USERNAME"
+	then
+		eprintf "FILE_IO_USERNAME not set in config [$file]"
+		exit 1
+	fi
+
+	if test -z "$FILE_IO_PASSWORD"
+	then
+		eprintf "FILE_IO_PASSWORD not set in config [$file]"
+		exit 1
+	fi
+
+	if test -z "${FILE_IO_COMMAND+1}"
+	then
+		eprintf "FILE_IO_COMMAND not set in config [$file]"
+		exit 1
+	fi
+}
+
+check_user_exists ( )
+{
+	local user="$1"
+	local pass="$2"
+	local encrypt=$( perl -e 'print crypt( $ARGV[0], "password" )' $pass )
+	local found=$( getent passwd $user 2>/dev/null )
+	local home_dir=
+
+	echo "checking if user [$user] exists..."
+
+	if test -z "$found"
+	then
+		echo "user [$user] not found, creating..."
+		sudo "useradd" -m -s /usr/lib/sftp-server -p $encrypt -G fileio-filetransfer $user
+		home_dir=$( getent passwd $user | cut -f6 -d: )		
+
+		sudo mkdir -p $home_dir/file-io/
+		sudo chown root:root $home_dir
+		sudo chmod 755 $home_dir
+		sudo chmod go-w $home_dir
+		sudo chown -R $user:fileio-filetransfer $home_dir/file-io
+	fi
+}
+
+check_user_incoming_dir_exists ( )
+{
+	local user="$1"
+	local incoming_dir="$2"
+	local home_dir=
+
+	echo "checking incoming directory exists..."
+	home_dir=$( getent passwd $user | cut -f6 -d: )
+
+	if ! test -d $home_dir/file-io/$incoming_dir
+	then
+		echo "directory $home_dir/file-io/$incoming_dir not found, creating..."
+		sudo mkdir -p $home_dir/file-io/$incoming_dir/tmp
+		sudo chown -R $user:fileio-filetransfer $home_dir/file-io/$incoming_dir
+	fi
 }
 
 enable_config ( )
@@ -43,6 +157,17 @@ enable_config ( )
 		printf "config [$conf_name] already enabled\n"
 		return
 	fi
+
+	source $instance_config
+
+	verify_config "$instance_config"
+
+	local user=$FILE_IO_USERNAME
+	local pass=$FILE_IO_PASSWORD
+	local incoming_dir=$FILE_IO_INCOMING_DIR
+
+	check_user_exists "$user" "$pass"
+	check_user_incoming_dir_exists "$user" "$incoming_dir"
 
 	ln -s $instance_config $file_io_config
 	printf "config [$conf_name] enabled\n"
@@ -86,11 +211,11 @@ cmd_disable ( )
 		local confs=$( find $instance_dir/file-io -type f -name "*.file-io" -printf "%f\n" 2>/dev/null )
 		for i in $confs
 		do
-			disable_config "$i" "$dir/conf/$entity-$location-$part-$instance-$i"
+			disable_config "$dir/conf/" "$i" "$dir/conf/$entity-$location-$part-$instance-$i"
 		done
 		
 	else
-		disable_config "$config_name" "$dir/conf/$entity-$location-$part-$instance-$config_name"
+		disable_config "$dir/conf/" "$config_name" "$dir/conf/$entity-$location-$part-$instance-$config_name"
 	fi
 }
 
diff --git a/src/libexec/file-io-daemon b/src/libexec/file-io-daemon
--- a/src/libexec/file-io-daemon
+++ b/src/libexec/file-io-daemon
@@ -4,6 +4,14 @@ pid=$$
 
 echo "file-io daemon ($pid) started"
 
+declare -a INCOMING_DIR
+declare -a OUTGOING_DIR
+declare -a DIR_REVERSED
+declare -a FILE_REGEX
+declare -a USERNAME
+declare -a PASSWORD
+declare -a COMMAND
+
 cleanup ( )
 {
 	echo "file-io daemon caught TERM signal"
@@ -13,8 +21,195 @@ cleanup ( )
 
 trap 'cleanup' TERM
 
-while true
-do
-	echo "daemon running..."
-	sleep 5
-done
+load_configs ( )
+{
+	echo "looking for configs.."
+	local i=0
+	local configs=$( find ../conf/ -type l -name "*.file-io" )
+	for c in $configs
+	do
+		
+		unset FILE_IO_INCOMING_DIR
+		unset FILE_IO_OUTGOING_DIR
+		unset FILE_IO_DIR_REVERSED
+		unset FILE_IO_REGEX
+		unset FILE_IO_USERNAME
+		unset FILE_IO_PASSWORD
+		unset FILE_IO_COMMAND
+
+		echo "config: $c"
+		source $c
+
+		if test -z "$FILE_IO_INCOMING_DIR"
+		then
+			printf "ERROR: FILE_IO_INCOMING_DIR not specified in config $c\n"
+			exit 1
+		fi
+
+		if test -z "$FILE_IO_OUTGOING_DIR"
+		then
+			printf "ERROR: FILE_IO_OUTGOING_DIR not specified in config $c\n"
+			exit 1
+		fi
+
+		if test -z "$FILE_IO_DIR_REVERSED"
+		then
+			printf "ERROR: FILE_IO_DIR_REVERSED not specified in config $c\n"
+			exit 1
+		fi
+
+		if test -z "$FILE_IO_REGEX"
+		then
+			printf "ERROR: FILE_IO_REGEX not specified in config $c\n"
+			exit 1
+		fi
+
+		if test -z "$FILE_IO_USERNAME"
+		then
+			printf "ERROR: FILE_IO_USERNAME not specified in config $c\n"
+			exit 1
+		fi
+
+		if test -z "$FILE_IO_PASSWORD"
+		then
+			printf "ERROR: FILE_IO_PASSWORD not specified in config $c\n"
+			exit 1
+		fi
+
+		if test -z ${FILE_IO_COMMAND+1}
+		then
+			printf "ERROR: FILE_IO_COMMAND not specified in config $c\n"
+			exit 1
+		fi
+
+		INCOMING_DIR[$i]=$FILE_IO_INCOMING_DIR
+		OUTGOING_DIR[$i]=$FILE_IO_OUTGOING_DIR
+		DIR_REVERSED[$i]=$FILE_IO_DIR_REVERSED
+		FILE_REGEX[$i]=$FILE_IO_REGEX
+		USERNAME[$i]=$FILE_IO_USERNAME
+		PASSWORD[$i]=$FILE_IO_PASSWORD
+		COMMAND[$i]=$FILE_IO_COMMAND
+
+		i=$(( i + 1 ))
+	done
+}
+
+verify_system( )
+{
+	local found=$( cat /etc/shells | grep "^/usr/lib/sftp-server" )
+	if test -z "$found"
+	then
+		printf "Adding '/usr/lib/sftp-server' to /etc/shells\n"
+		echo "/usr/lib/sftp-server" >> /etc/shells
+	else
+		printf "Found '/usr/lib/sftp-server' in /etc/shells, not adding\n"
+	fi
+}
+
+create_user ( )
+{
+	local index=$1
+	local user=
+	local pass=
+	local home_dir=
+
+	if test -z "$index"
+	then
+		printf "ERROR: no index provided to create_user\n"
+		exit 1
+	fi
+
+
+	######## CHANGE THE USERS HOME DIRECTORY to /home/username to fix ssh permissions shit.
+
+	user=${USERNAME[$index]}
+	pass=$( perl -e 'print crypt( $ARGV[0], "password" )' ${PASSWORD[$index]} )
+	home_dir=$( cd ../users/ && pwd )/$user
+
+	echo "user: $user"
+	echo "pass: ${PASSWORD[$index]}"
+	echo "home: $home_dir"
+
+	mkdir -p $home_dir/${INCOMING_DIR[$index]}/tmp
+	chmod -R 774 $home_dir
+
+	useradd -d $home_dir -m -s /usr/lib/sftp-server -p $pass -G fileio-filetransfer $user
+
+	chown root:root $home_dir
+	chmod 755 $home_dir
+	chmod go-w $home_dir
+
+	chown -R $user:fileio-filetransfer $home_dir/${INCOMING_DIR[$index]}
+	chmod ug+rwX $home_dir/${INCOMING_DIR[$index]}
+}
+
+verify_user ( )
+{
+	local index=$1
+	local found=
+
+	if test -z "$index"
+	then
+		printf "ERROR: no index provided to verify_user\n"
+		exit 1
+	fi
+
+	sed -i 's,Subsystem sftp /usr/lib/openssh/sftp-server,Subsystem sftp internal-sftp,' /etc/ssh/sshd_config
+
+	found=$( grep "Match group fileio-filetransfer" /etc/ssh/sshd_config )
+	if test -z "$found"
+	then
+		echo "" >> /etc/ssh/sshd_config
+		echo "Match group fileio-filetransfer" >> /etc/ssh/sshd_config
+		echo "  ChrootDirectory %h" >> /etc/ssh/sshd_config
+		echo "  X11Forwarding no" >> /etc/ssh/sshd_config
+		echo "  AllowTcpForwarding no" >> /etc/ssh/sshd_config
+		echo "  ForceCommand internal-sftp" >> /etc/ssh/sshd_config
+	fi
+
+	found=
+	found=$( cat /etc/group | grep "^fileio-filetransfer:" )
+	if test -z "$found"
+	then
+		groupadd --system fileio-filetransfer
+	fi
+}
+
+verify_config ( )
+{
+	local len=${#USERNAME[@]}
+	local found=
+	local user=
+	local i=0
+
+	while test $i -lt $len
+	do
+		user=${USERNAME[$i]}
+		printf "Username: %s\n" $user
+
+		found=$( cat /etc/passwd | grep "^$user:" )
+		if test -z "$found"
+		then
+			printf "  found: false\n"
+			create_user $i
+		else
+			printf "  found: true\n"
+			verify_user $i
+		fi
+
+		i=$(( i + 1 ))
+	done
+}
+
+loop ( )
+{
+	while true 
+	do
+		echo "Inside loop"
+		sleep 5
+	done
+}
+
+load_configs
+verify_system
+verify_config
